from ..views import index
from ..views import Configuring_and_Installing_Node_js
from ..views import How_to_Activate_the_Product
from ..views import Exporting_a_Report_from_Code
from ..views import Exporting_a_Report_from_Code_on_the_Server_Side
from ..views import Registering_a_Data_from_Code
from ..views import Showing_a_Report_in_the_Viewer
from ..views import Showing_a_Report_in_the_Viewer_in_an_HTML_template
from ..views import Editing_a_Report_Template_in_the_Designer
from ..views import Editing_a_Report_Template_in_the_Designer_in_an_HTML_template
